services:
  # Backend API
  - type: web
    name: desafio-autou-back
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.interfaces.api.app_factory:create_app --host 0.0.0.0 --port $PORT --factory
    envVars:
      - key: ENV
        value: prod
      - key: AI_PROVIDER
        value: gemini
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health

  # Frontend
  - type: web
    name: desafio-autou
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://desafio-autou-back-fxvg.onrender.com
